---
keybinds:
    unbind: true
    normal:
        - action: [SwitchToMode: Tmux,]
          key: [Ctrl: 'q',]
        - action: [MoveFocus: Left, SwitchToMode: Normal,]
          key: [ Alt: 'h']
        - action: [MoveFocus: Right, SwitchToMode: Normal,]
          key: [ Alt: 'l']
        - action: [MoveFocus: Down, SwitchToMode: Normal,]
          key: [ Alt: 'j']
        - action: [MoveFocus: Up, SwitchToMode: Normal,]
          key: [ Alt: 'k']

    scroll:
        - action: [EditScrollback, SwitchToMode: Normal]
          key: [Char: 'e']
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g', Esc]
        - action: [ScrollToBottom, SwitchToMode: Normal,]
          key: [Ctrl: 'c',]
        - action: [ScrollDown,]
          key: [Char: 'j', Down,]
        - action: [ScrollUp,]
          key: [Char: 'k', Up,]
        - action: [PageScrollDown,]
          key: [Char: 'f', PageDown,]
        - action: [PageScrollUp,]
          key: [Char: 'b', PageUp,]
        - action: [HalfPageScrollDown,]
          key: [Ctrl: 'd',]
        - action: [HalfPageScrollUp,]
          key: [Ctrl: 'u',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h']
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l']
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j']
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k']
        # uncomment this and adjust key if using copy_on_select=false
        - action: [Copy: ]
          key: [ Char: 'y']
        - action: [SwitchToMode: EnterSearch, SearchInput: [0],]
          key: [Char: '/']
    entersearch:
        - action: [SwitchToMode: Search,]
          key: [Char: "\n"]
        - action: [SearchInput: [27], SwitchToMode: Scroll,]
          key: [Ctrl: 'c', Esc]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
    search:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g', Esc]
        - action: [ScrollDown,]
          key: [Char: 'j',]
        - action: [ScrollUp,]
          key: [Char: 'k',]
        - action: [PageScrollDown,]
          key: [Char: 'f', PageDown,]
        - action: [PageScrollUp,]
          key: [Char: 'b', PageUp,]
        - action: [HalfPageScrollDown,]
          key: [Ctrl: 'd',]
        - action: [HalfPageScrollUp,]
          key: [Ctrl: 'u',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [SwitchToMode: EnterSearch, SearchInput: [0],]
          key: [Char: "\n"]
        - action: [Search: Down]
          key: [Char: 'n']
        - action: [Search: Up]
          key: [Char: 'p']
        - action: [SearchToggleOption: CaseSensitivity]
          key: [Char: 'c']
        - action: [SearchToggleOption: Wrap]
          key: [Char: 'w']
        - action: [SearchToggleOption: WholeWord]
          key: [Char: 'o']
    tmux:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'g', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [ Char: '[']
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: "v",]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: 'h',]
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'c',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: ',']
        - action: [GoToPreviousTab, SwitchToMode: Normal,]
          key: [ Char: 'p']
        - action: [GoToNextTab, SwitchToMode: Normal,]
          key: [ Char: 'n']
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        - action: [MoveFocusOrTab: Left,]
          key: [ Alt: 'h', Alt: Left]
        - action: [MoveFocusOrTab: Right,]
          key: [ Alt: 'l', Alt: Right]
        - action: [MoveFocus: Down,]
          key: [ Alt: 'j', Alt: Down]
        - action: [MoveFocus: Up,]
          key: [ Alt: 'k', Alt: Up]
        - action: [FocusNextPane,]
          key: [ Char: 'o']
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        - action: [Detach,]
          key: [Char: 'd',]

pane_frames: false
copy_on_select: false
